"""create raw tables

Revision ID: 05a27af460f9
Revises: 
Create Date: 2026-09-15 12:25:31.326990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05a27af460f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('customer_unique_id', sa.String(), nullable=True),
    sa.Column('customer_zip_code_prefix', sa.String(), nullable=True),
    sa.Column('customer_city', sa.String(), nullable=True),
    sa.Column('customer_state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('orders',
    sa.Column('order_unique_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('seller_id', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('freight_value', sa.Float(), nullable=True),
    sa.Column('order_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('order_unique_id')
    )
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('payment_type', sa.String(), nullable=True),
    sa.Column('payment_sequential', sa.Integer(), nullable=True),
    sa.Column('payment_installments', sa.Integer(), nullable=True),
    sa.Column('payment_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('product_category_name', sa.String(), nullable=True),
    sa.Column('product_name_lenght', sa.Float(), nullable=True),
    sa.Column('product_description_lenght', sa.Float(), nullable=True),
    sa.Column('product_photos_qty', sa.Integer(), nullable=True),
    sa.Column('product_weight_g', sa.Float(), nullable=True),
    sa.Column('product_length_cm', sa.Float(), nullable=True),
    sa.Column('product_height_cm', sa.Float(), nullable=True),
    sa.Column('product_width_cm', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('sellers',
    sa.Column('seller_id', sa.String(), nullable=False),
    sa.Column('seller_city', sa.String(), nullable=True),
    sa.Column('seller_state', sa.String(), nullable=True),
    sa.Column('seller_zip_code_prefix', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('seller_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sellers')
    op.drop_table('products')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('customers')
    # ### end Alembic commands ###
