"""audit_models

Revision ID: 0cfbed74a25a
Revises: 872f63d4dfb5
Create Date: 2026-09-19 13:08:18.657129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cfbed74a25a'
down_revision: Union[str, Sequence[str], None] = '872f63d4dfb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_name', sa.String(length=100), nullable=False),
    sa.Column('source_file', sa.String(length=500), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', name='pipeline_status'), server_default=sa.text("'RUNNING'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('raw_load_audit',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('source_row_count', sa.Integer(), nullable=False),
    sa.Column('rows_after_deduplication', sa.Integer(), nullable=False),
    sa.Column('inserted_row_count', sa.Integer(), nullable=False),
    sa.Column('skipped_row_count', sa.Integer(), nullable=False),
    sa.Column('failed_row_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', name='pipeline_status'), server_default=sa.text("'RUNNING'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.run_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('audit_id'),
    sa.UniqueConstraint('run_id', 'table_name', name='uq_raw_load_audit_run_table')
    )
    op.create_index(op.f('ix_raw_load_audit_run_id'), 'raw_load_audit', ['run_id'], unique=False)
    op.create_table('validation_audit',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('checked_row_count', sa.Integer(), nullable=False),
    sa.Column('failed_row_count', sa.Integer(), nullable=False),
    sa.Column('sample_invalid_rows', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.run_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('audit_id'),
    sa.UniqueConstraint('run_id', 'table_name', 'rule_name', name='uq_validation_audit_run_table_rule')
    )
    op.create_index(op.f('ix_validation_audit_run_id'), 'validation_audit', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_audit_run_id'), table_name='validation_audit')
    op.drop_table('validation_audit')
    op.drop_index(op.f('ix_raw_load_audit_run_id'), table_name='raw_load_audit')
    op.drop_table('raw_load_audit')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
