"""orders_n_order_items_table

Revision ID: 872f63d4dfb5
Revises: 05a27af460f9
Create Date: 2026-09-17 11:53:20.635672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872f63d4dfb5'
down_revision: Union[str, Sequence[str], None] = '05a27af460f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('order_unique_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('seller_id', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('freight_value', sa.Float(), nullable=True),
    sa.Column('order_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('order_unique_id'),
    sa.UniqueConstraint('order_id', 'order_item_id', name='uq_order_items_order_id_item_id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.add_column('orders', sa.Column('order_purchase_timestamp', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('order_approved_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('order_delivered_carrier_date', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('order_delivered_customer_date', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('order_estimated_delivery_date', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('shipping_limit_date', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_column('orders', 'order_item_id')
    op.drop_column('orders', 'price')
    op.drop_column('orders', 'order_status')
    op.drop_column('orders', 'customer_id')
    op.drop_column('orders', 'freight_value')
    op.drop_column('orders', 'seller_id')
    op.drop_column('orders', 'product_id')
    op.drop_column('orders', 'order_unique_id')
    op.create_unique_constraint('uq_payments_order_id_sequential', 'payments', ['order_id', 'payment_sequential'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS order_items CASCADE")
    op.execute("DROP TABLE IF EXISTS orders CASCADE")   
    # ### end Alembic commands ###
