"""analytics_models

Revision ID: c0ba64fcecb2
Revises: 0cfbed74a25a
Create Date: 2026-09-21 12:56:43.471661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ba64fcecb2'
down_revision: Union[str, Sequence[str], None] = '0cfbed74a25a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_customer',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('customer_unique_id', sa.String(), nullable=True),
    sa.Column('customer_zip_code_prefix', sa.String(), nullable=True),
    sa.Column('customer_city', sa.String(), nullable=True),
    sa.Column('customer_state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('dim_date',
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('full_date', sa.Date(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('day_name', sa.String(), nullable=False),
    sa.Column('month_number', sa.Integer(), nullable=False),
    sa.Column('month_name', sa.String(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date_id'),
    sa.UniqueConstraint('full_date')
    )
    op.create_table('dim_product',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('product_category_name', sa.String(), nullable=True),
    sa.Column('product_name_length', sa.Float(), nullable=True),
    sa.Column('product_description_length', sa.Float(), nullable=True),
    sa.Column('product_photos_qty', sa.Integer(), nullable=True),
    sa.Column('product_weight_g', sa.Float(), nullable=True),
    sa.Column('product_length_cm', sa.Float(), nullable=True),
    sa.Column('product_height_cm', sa.Float(), nullable=True),
    sa.Column('product_width_cm', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('dim_seller',
    sa.Column('seller_id', sa.String(), nullable=False),
    sa.Column('seller_city', sa.String(), nullable=True),
    sa.Column('seller_state', sa.String(), nullable=True),
    sa.Column('seller_zip_code_prefix', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('seller_id')
    )
    op.create_table('fact_order_items',
    sa.Column('fact_order_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('seller_id', sa.String(), nullable=False),
    sa.Column('purchase_date_id', sa.Integer(), nullable=False),
    sa.Column('order_status', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('freight_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('item_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivery_days', sa.Integer(), nullable=True),
    sa.Column('delivered_late', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['dim_customer.customer_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['dim_product.product_id'], ),
    sa.ForeignKeyConstraint(['purchase_date_id'], ['dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['dim_seller.seller_id'], ),
    sa.PrimaryKeyConstraint('fact_order_item_id'),
    sa.UniqueConstraint('order_id', 'order_item_id', name='uq_fact_order_items_order_item')
    )
    op.create_index(op.f('ix_fact_order_items_customer_id'), 'fact_order_items', ['customer_id'], unique=False)
    op.create_index(op.f('ix_fact_order_items_order_id'), 'fact_order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_fact_order_items_product_id'), 'fact_order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_fact_order_items_purchase_date_id'), 'fact_order_items', ['purchase_date_id'], unique=False)
    op.create_index(op.f('ix_fact_order_items_seller_id'), 'fact_order_items', ['seller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_order_items_seller_id'), table_name='fact_order_items')
    op.drop_index(op.f('ix_fact_order_items_purchase_date_id'), table_name='fact_order_items')
    op.drop_index(op.f('ix_fact_order_items_product_id'), table_name='fact_order_items')
    op.drop_index(op.f('ix_fact_order_items_order_id'), table_name='fact_order_items')
    op.drop_index(op.f('ix_fact_order_items_customer_id'), table_name='fact_order_items')
    op.drop_table('fact_order_items')
    op.drop_table('dim_seller')
    op.drop_table('dim_product')
    op.drop_table('dim_date')
    op.drop_table('dim_customer')
    # ### end Alembic commands ###
